# Site settings
title: Katrina Hussain
email: me@katrinah.io
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://katrinah.io" # the base hostname & protocol for your site
twitter_username: trinabhu
github_username:  KatrinaH
linkedin_username: 
googlePlus_username: KatrinaHussain

# Build settings
markdown: kramdown
gems: ["bourbon", "neat"]
exclude: ["Gemfile", "config.codekit", "Gemfile.lock", "README.md"]
